version: '3.8'

services:
  database:
    container_name: symfony-microservices-database
    working_dir: /app
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony-microservices-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - .:/app
      - ./mysql:/var/lib/mysql
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password 

  nginx:
    container_name: symfony-microservices-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    container_name: symfony-parcel-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - database
